// generated by import-objects.py - the pictures of the actors, where they lie in the US ROM (assets.json)
#pragma once
#include <stdint.h>

// a texture in a model: the index of its picture in the table below (an array of one so the display-list
// macros take its address the way they took the picture's)
typedef struct SM64TexRef { int32_t id; } SM64TexRef;

struct SM64ActorTexture { const char *name; uint16_t w, h; uint8_t fmt, bits; uint32_t mio0, offset; };
extern const struct SM64ActorTexture gActorTextures[];
extern const int32_t gActorTextureCount;

