// generated by import-objects.py
#pragma once
#include "types.h"
// an entry: its behaviour, its geo layout (NULL: nothing to draw), the model id the behaviour may know it by,
// the behaviour parameters, the level it believes it is in, and an entry spawned first at the same place (-1: none)
struct SM64MenuEntry { const char *name; const char *category; const BehaviorScript *behavior; const GeoLayout *geo; int32_t model; uint32_t bhvParams; int32_t level; int32_t companion; };
extern const struct SM64MenuEntry gMenuEntries[];
extern const int32_t gMenuEntryCount;
