// generated by import-objects.py - what the spawn menu offers
#include "ultra64.h"
#include "sm64.h"
#include "behavior_data.h"
#include "model_ids.h"
#include "level_table.h"
#include "actors/common0.h"
#include "actors/common1.h"
#include "actors/group0.h"
#include "actors/group1.h"
#include "actors/group2.h"
#include "actors/group3.h"
#include "actors/group4.h"
#include "actors/group5.h"
#include "actors/group6.h"
#include "actors/group7.h"
#include "actors/group8.h"
#include "actors/group9.h"
#include "actors/group10.h"
#include "actors/group11.h"
#include "actors/group12.h"
#include "actors/group13.h"
#include "actors/group14.h"
#include "actors/group15.h"
#include "actors/group16.h"
#include "actors/group17.h"
#include "menu_table.h"

const struct SM64MenuEntry gMenuEntries[] = {
    { "GOOMBA", "ENEMIES", bhvGoomba, goomba_geo, 0xC0, 0x00000000, 0, -1 },
    { "HUGE GOOMBA", "ENEMIES", bhvGoomba, goomba_geo, 0xC0, 0x00010000, 0, -1 },
    { "TINY GOOMBA", "ENEMIES", bhvGoomba, goomba_geo, 0xC0, 0x00020000, 0, -1 },
    { "GOOMBA TRIPLET", "ENEMIES", bhvGoombaTripletSpawner, NULL, 0x00, 0x00000000, 0, -1 },
    { "KOOPA", "ENEMIES", bhvKoopa, koopa_with_shell_geo, 0x68, 0x00010000, 0, -1 },
    { "KOOPA WITHOUT SHELL", "ENEMIES", bhvKoopa, koopa_without_shell_geo, 0xBF, 0x00000000, 0, -1 },
    { "TINY KOOPA", "ENEMIES", bhvKoopa, koopa_with_shell_geo, 0x68, 0x00040000, 0, -1 },
    { "BOB-OMB", "ENEMIES", bhvBobomb, black_bobomb_geo, 0xBC, 0x00000000, 0, -1 },
    { "BULLY", "ENEMIES", bhvSmallBully, bully_geo, 0x56, 0x00000000, 0, -1 },
    { "CHILL BULLY", "ENEMIES", bhvSmallChillBully, chilly_chief_geo, 0x64, 0x00000000, 0, -1 },
    { "CHUCKYA", "ENEMIES", bhvChuckya, chuckya_geo, 0xDF, 0x00000000, 0, -1 },
    { "HEAVE-HO", "ENEMIES", bhvHeaveHo, heave_ho_geo, 0x59, 0x00000000, 0, -1 },
    { "AMP", "ENEMIES", bhvHomingAmp, dAmpGeo, 0xC2, 0x00000000, 0, -1 },
    { "CIRCLING AMP", "ENEMIES", bhvCirclingAmp, dAmpGeo, 0xC2, 0x00020000, 0, -1 },
    { "BOO", "ENEMIES", bhvBoo, boo_geo, 0x54, 0x00000000, 0, -1 },
    { "BOO WITH CAGE", "ENEMIES", bhvBooWithCage, boo_geo, 0x54, 0x00000000, 0, -1 },
    { "COURTYARD BOOS", "ENEMIES", bhvCourtyardBooTriplet, boo_castle_geo, 0x65, 0x00000000, 0, -1 },
    { "FLYING BOOKEND", "ENEMIES", bhvFlyingBookend, bookend_geo, 0x59, 0x00000000, 0, -1 },
    { "HAUNTED CHAIR", "ENEMIES", bhvHauntedChair, haunted_chair_geo, 0x56, 0x00000000, 0, -1 },
    { "MAD PIANO", "ENEMIES", bhvMadPiano, mad_piano_geo, 0x57, 0x00000000, 0, -1 },
    { "BULLET BILL", "ENEMIES", bhvBulletBill, bullet_bill_geo, 0x54, 0x00000000, 0, -1 },
    { "CHAIN CHOMP", "ENEMIES", bhvChainChomp, chain_chomp_geo, 0x66, 0x00000000, 0, -1 },
    { "PIRANHA PLANT", "ENEMIES", bhvPiranhaPlant, piranha_plant_geo, 0x64, 0x00000000, 0, -1 },
    { "FIRE PIRANHA PLANT", "ENEMIES", bhvFirePiranhaPlant, piranha_plant_geo, 0x64, 0x00000000, 0, -1 },
    { "FLY GUY", "ENEMIES", bhvFlyGuy, flyguy_geo, 0xDC, 0x00000000, 0, -1 },
    { "KLEPTO", "ENEMIES", bhvKlepto, klepto_geo, 0x57, 0x00000000, 0, -1 },
    { "LAKITU", "ENEMIES", bhvEnemyLakitu, enemy_lakitu_geo, 0x54, 0x00000000, 0, -1 },
    { "SPINY", "ENEMIES", bhvSpiny, spiny_geo, 0x56, 0x00000000, 0, -1 },
    { "MONTY MOLE", "ENEMIES", bhvMontyMole, monty_mole_geo, 0x55, 0x00000000, 0, 29 },
    { "MONTY MOLE HOLE", "ENEMIES", bhvMontyMoleHole, NULL, 0x54, 0x00000000, 0, -1 },
    { "MR I", "ENEMIES", bhvMrI, mr_i_geo, 0x67, 0x00000000, 0, -1 },
    { "MR BLIZZARD", "ENEMIES", bhvMrBlizzard, mr_blizzard_geo, 0x56, 0x00010000, 0, -1 },
    { "POKEY", "ENEMIES", bhvPokey, pokey_head_geo, 0x54, 0x00000000, 0, -1 },
    { "SCUTTLEBUG", "ENEMIES", bhvScuttlebug, scuttlebug_geo, 0x65, 0x00000000, 0, -1 },
    { "SKEETER", "ENEMIES", bhvSkeeter, skeeter_geo, 0x69, 0x00000000, 0, -1 },
    { "SNUFIT", "ENEMIES", bhvSnufit, snufit_geo, 0xCE, 0x00000000, 0, -1 },
    { "SPINDRIFT", "ENEMIES", bhvSpindrift, spindrift_geo, 0x54, 0x00000000, 0, -1 },
    { "SWOOP", "ENEMIES", bhvSwoop, swoop_geo, 0x64, 0x00000000, 0, -1 },
    { "THWOMP", "ENEMIES", bhvThwomp, thwomp_geo, 0x58, 0x00000000, 0, -1 },
    { "WHOMP", "ENEMIES", bhvSmallWhomp, whomp_geo, 0x67, 0x00000000, 0, -1 },
    { "BUBBA", "ENEMIES", bhvBubba, bubba_geo, 0x59, 0x00000000, 0, -1 },
    { "SUSHI SHARK", "ENEMIES", bhvSushiShark, sushi_geo, 0x56, 0x00000000, 0, -1 },
    { "UNAGI", "ENEMIES", bhvUnagi, unagi_geo, 0x55, 0x00000000, 0, -1 },
    { "CLAM", "ENEMIES", bhvClamShell, clam_shell_geo, 0x58, 0x00000000, 0, -1 },
    { "MANTA RAY", "ENEMIES", bhvMantaRay, manta_seg5_geo_05008D14, 0x54, 0x00000000, 0, -1 },
    { "WATER BOMB CANNON", "ENEMIES", bhvWaterBombCannon, NULL, 0x00, 0x00000000, 0, -1 },
    { "BOWLING BALL", "ENEMIES", bhvFreeBowlingBall, bowling_ball_geo, 0xB4, 0x00000000, 0, -1 },
    { "FLAME THROWER", "ENEMIES", bhvFlamethrower, NULL, 0x00, 0x00000000, 0, -1 },
    { "FIRE SPITTER", "ENEMIES", bhvFireSpitter, NULL, 0x00, 0x00000000, 0, -1 },
    { "SNOWMAN", "ENEMIES", bhvSLSnowmanWind, NULL, 0x00, 0x00000000, 0, -1 },
    { "MONEYBAG", "ENEMIES", bhvMoneybag, moneybag_geo, 0x66, 0x00000000, 0, -1 },
    { "UKIKI", "ENEMIES", bhvUkiki, ukiki_geo, 0x56, 0x00000000, 0, -1 },
    { "KING BOB-OMB", "BOSSES", bhvKingBobomb, king_bobomb_geo, 0x56, 0x00000000, 0, -1 },
    { "WHOMP KING", "BOSSES", bhvWhompKingBoss, whomp_geo, 0x67, 0x00000000, 0, -1 },
    { "BIG BULLY", "BOSSES", bhvBigBully, bully_boss_geo, 0x57, 0x00000000, 0, -1 },
    { "BIG BULLY AND MINIONS", "BOSSES", bhvBigBullyWithMinions, bully_boss_geo, 0x57, 0x00000000, 0, -1 },
    { "BIG CHILL BULLY", "BOSSES", bhvBigChillBully, chilly_chief_big_geo, 0x65, 0x00000000, 0, -1 },
    { "BIG BOO", "BOSSES", bhvBalconyBigBoo, boo_geo, 0x54, 0x00000000, 0, -1 },
    { "BIG MR I", "BOSSES", bhvMrI, mr_i_geo, 0x67, 0x00010000, 0, -1 },
    { "WIGGLER", "BOSSES", bhvWigglerHead, wiggler_head_geo, 0x57, 0x00000000, 0, -1 },
    { "EYEROK", "BOSSES", bhvEyerokBoss, NULL, 0x00, 0x00000000, 0, -1 },
    { "BOWSER DARK WORLD", "BOSSES", bhvBowser, bowser_geo, 0x64, 0x00000000, LEVEL_BITDW, -1 },
    { "BOWSER FIRE SEA", "BOSSES", bhvBowser, bowser_geo, 0x64, 0x00000000, LEVEL_BITFS, -1 },
    { "BOWSER IN THE SKY", "BOSSES", bhvBowser, bowser_geo, 0x64, 0x00000000, LEVEL_BITS, -1 },
    { "BOWSER MINE", "BOSSES", bhvBowserBomb, bowser_bomb_geo, 0xB3, 0x00000000, 0, -1 },
    { "COIN", "ITEMS", bhvYellowCoin, yellow_coin_geo, 0x74, 0x00000000, 0, -1 },
    { "RED COIN", "ITEMS", bhvRedCoin, red_coin_geo, 0xD7, 0x00000000, 0, -1 },
    { "BLUE COIN", "ITEMS", bhvBlueCoinJumping, blue_coin_geo, 0x76, 0x00000000, 0, -1 },
    { "COIN RING", "ITEMS", bhvCoinFormation, NULL, 0x00, 0x00020000, 0, -1 },
    { "COIN LINE", "ITEMS", bhvCoinFormation, NULL, 0x00, 0x00000000, 0, -1 },
    { "1UP MUSHROOM", "ITEMS", bhv1Up, mushroom_1up_geo, 0xD4, 0x00000000, 0, -1 },
    { "POWER STAR", "ITEMS", bhvStar, star_geo, 0x7A, 0x00000000, 0, -1 },
    { "WING CAP", "ITEMS", bhvWingCap, marios_wing_cap_geo, 0x87, 0x00000000, 0, -1 },
    { "METAL CAP", "ITEMS", bhvMetalCap, marios_metal_cap_geo, 0x86, 0x00000000, 0, -1 },
    { "VANISH CAP", "ITEMS", bhvVanishCap, marios_cap_geo, 0x88, 0x00000000, 0, -1 },
    { "HEART", "ITEMS", bhvRecoveryHeart, heart_geo, 0x00, 0x00000000, 0, -1 },
    { "BOX WITH WING CAP", "ITEMS", bhvExclamationBox, exclamation_box_geo, 0x89, 0x00000000, 0, -1 },
    { "BOX WITH METAL CAP", "ITEMS", bhvExclamationBox, exclamation_box_geo, 0x89, 0x00010000, 0, -1 },
    { "BOX WITH VANISH CAP", "ITEMS", bhvExclamationBox, exclamation_box_geo, 0x89, 0x00020000, 0, -1 },
    { "BOX WITH KOOPA SHELL", "ITEMS", bhvExclamationBox, exclamation_box_geo, 0x89, 0x00030000, 0, -1 },
    { "BOX WITH COINS", "ITEMS", bhvExclamationBox, exclamation_box_geo, 0x89, 0x00060000, 0, -1 },
    { "BOX WITH 1UP", "ITEMS", bhvExclamationBox, exclamation_box_geo, 0x89, 0x00070000, 0, -1 },
    { "BOX WITH STAR", "ITEMS", bhvExclamationBox, exclamation_box_geo, 0x89, 0x00080000, 0, -1 },
    { "KOOPA SHELL", "ITEMS", bhvKoopaShell, koopa_shell_geo, 0xBE, 0x00000000, 0, -1 },
    { "BREAKABLE BOX", "ITEMS", bhvBreakableBox, breakable_box_geo, 0x81, 0x00000000, 0, -1 },
    { "SMALL BOX", "ITEMS", bhvBreakableBoxSmall, breakable_box_small_geo, 0x82, 0x00000000, 0, -1 },
    { "CRAZY BOX", "ITEMS", bhvJumpingBox, breakable_box_small_geo, 0x82, 0x00000000, 0, -1 },
    { "METAL BOX", "ITEMS", bhvPushableMetalBox, metal_box_geo, 0xD9, 0x00000000, 0, -1 },
    { "FLAME", "HAZARDS", bhvFlame, red_flame_geo, 0x90, 0x00000000, 0, -1 },
    { "BLUE FLAME", "HAZARDS", bhvFlame, blue_flame_geo, 0x91, 0x00000000, 0, -1 },
    { "BOUNCING FIREBALL", "HAZARDS", bhvBouncingFireball, NULL, 0x00, 0x00000000, 0, -1 },
    { "TWEESTER", "HAZARDS", bhvTweester, tweester_geo, 0x56, 0x00000000, 0, -1 },
    { "WATER BOMB", "HAZARDS", bhvWaterBomb, water_bomb_geo, 0x54, 0x00000000, 0, -1 },
    { "BOB-OMB BUDDY", "CREATURES", bhvBobombBuddy, bobomb_buddy_geo, 0xC3, 0x00000000, 0, -1 },
    { "TOAD", "CREATURES", bhvToadMessage, toad_geo, 0xDD, 0x00000000, 0, -1 },
    { "YOSHI", "CREATURES", bhvYoshi, yoshi_geo, 0x55, 0x00000000, 0, -1 },
    { "MIPS", "CREATURES", bhvMips, mips_geo, 0x64, 0x00000000, 0, -1 },
    { "HOOT", "CREATURES", bhvHoot, hoot_geo, 0x56, 0x00000000, 0, -1 },
    { "DORRIE", "CREATURES", bhvDorrie, dorrie_geo, 0x68, 0x00000000, 0, -1 },
    { "PENGUIN MOTHER", "CREATURES", bhvTuxiesMother, penguin_geo, 0x57, 0x00000000, 0, -1 },
    { "SMALL PENGUIN", "CREATURES", bhvSmallPenguin, penguin_geo, 0x57, 0x00000000, 0, -1 },
    { "WALKING PENGUIN", "CREATURES", bhvSLWalkingPenguin, penguin_geo, 0x57, 0x00000000, 0, -1 },
    { "BUTTERFLY", "CREATURES", bhvButterfly, butterfly_geo, 0xBB, 0x00000000, 0, -1 },
    { "FISH", "CREATURES", bhvFishSpawner, NULL, 0x00, 0x00000000, 0, -1 },
    { "SEAWEED", "CREATURES", bhvSeaweed, seaweed_geo, 0xC1, 0x00000000, 0, -1 },
    { "TREE", "OBJECTS", bhvTree, bubbly_tree_geo, 0x00, 0x00000000, 0, -1 },
    { "PALM TREE", "OBJECTS", bhvTree, palm_tree_geo, 0x00, 0x00000000, 0, -1 },
    { "SNOW TREE", "OBJECTS", bhvTree, snow_tree_geo, 0x00, 0x00000000, 0, -1 },
    { "SPIKY TREE", "OBJECTS", bhvTree, spiky_tree_geo, 0x00, 0x00000000, 0, -1 },
    { "SIGNPOST", "OBJECTS", bhvMessagePanel, wooden_signpost_geo, 0x7C, 0x00000000, 0, -1 },
    { "WOODEN POST", "OBJECTS", bhvWoodenPost, wooden_post_geo, 0x6B, 0x00000000, 0, -1 },
    { "CHECKERBOARD LIFT", "OBJECTS", bhvCheckerboardElevatorGroup, NULL, 0x00, 0x00000000, 0, -1 },
    { "TREASURE CHESTS", "OBJECTS", bhvTreasureChestsJRB, NULL, 0x00, 0x00000000, 0, -1 },
    { "CANNON", "OBJECTS", bhvCannon, cannon_base_geo, 0x80, 0x00000000, 0, -1 },
    { "WARP PIPE", "OBJECTS", bhvStaticObject, warp_pipe_geo, 0x49, 0x00000000, LEVEL_BITS, -1 },
    { "EXPLOSION", "OBJECTS", bhvExplosion, explosion_geo, 0xCD, 0x00000000, 0, -1 },
};
const int32_t gMenuEntryCount = 116;
