// generated by import-objects.py
#pragma once
#include "types.h"
struct SM64ModelBinding { int32_t level; int32_t model; const GeoLayout *geo; const Gfx *dl; int32_t layer; };
extern const struct SM64ModelBinding gModelBindings[];
